"""baseline schema of v0.1.0

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 11:49:44.047772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('max_domains', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_api_tokens', sa.Integer(), nullable=False),
    sa.Column('max_alert_rules', sa.Integer(), nullable=False),
    sa.Column('max_inbound_addresses', sa.Integer(), nullable=False),
    sa.Column('report_retention_days', sa.Integer(), nullable=False),
    sa.Column('smtp_rate_limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('api_rate_limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('smtp_inbound_rejections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('remote_ip', sa.String(length=45), nullable=True),
    sa.Column('attempted_recipient', sa.String(length=320), nullable=True),
    sa.Column('rejection_code', sa.String(length=10), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smtp_inbound_rejections_attempted_recipient'), 'smtp_inbound_rejections', ['attempted_recipient'], unique=False)
    op.create_index(op.f('ix_smtp_inbound_rejections_created_at'), 'smtp_inbound_rejections', ['created_at'], unique=False)
    op.create_index(op.f('ix_smtp_inbound_rejections_remote_ip'), 'smtp_inbound_rejections', ['remote_ip'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token', sa.String(length=100), nullable=True),
    sa.Column('password_reset_token', sa.String(length=100), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('max_domains', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_api_tokens', sa.Integer(), nullable=False),
    sa.Column('max_alert_rules', sa.Integer(), nullable=False),
    sa.Column('max_inbound_addresses', sa.Integer(), nullable=False),
    sa.Column('report_retention_days', sa.Integer(), nullable=False),
    sa.Column('smtp_rate_limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('api_rate_limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('api_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_organization_id'), 'api_tokens', ['organization_id'], unique=False)
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('app_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=False)
    op.create_index(op.f('ix_app_settings_organization_id'), 'app_settings', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_report_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dmarc_policy', sa.String(length=20), nullable=True),
    sa.Column('dmarc_policy_sp', sa.String(length=20), nullable=True),
    sa.Column('dmarc_policy_pct', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=False)
    op.create_index(op.f('ix_domains_organization_id'), 'domains', ['organization_id'], unique=False)
    op.create_table('notification_channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel_type', sa.String(length=30), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_channels_organization_id'), 'notification_channels', ['organization_id'], unique=False)
    op.create_table('organization_memberships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_memberships_organization_id'), 'organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False)
    op.create_table('source_ips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('pass_rate', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('classified_by', sa.String(length=36), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reverse_dns', sa.String(length=255), nullable=True),
    sa.Column('asn', sa.String(length=20), nullable=True),
    sa.Column('asn_org', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_ips_classification'), 'source_ips', ['classification'], unique=False)
    op.create_index(op.f('ix_source_ips_ip_address'), 'source_ips', ['ip_address'], unique=False)
    op.create_index(op.f('ix_source_ips_last_seen_at'), 'source_ips', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_source_ips_organization_id'), 'source_ips', ['organization_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('threshold_unit', sa.String(length=20), nullable=True),
    sa.Column('time_window_minutes', sa.Integer(), nullable=False),
    sa.Column('min_message_count', sa.Integer(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('notification_channel_ids', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_allowed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_alert_type'), 'alert_rules', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alert_rules_organization_id'), 'alert_rules', ['organization_id'], unique=False)
    op.create_table('inbound_mail_addresses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=36), nullable=True),
    sa.Column('address', sa.String(length=320), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('max_message_size', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_mail_addresses_address'), 'inbound_mail_addresses', ['address'], unique=True)
    op.create_index(op.f('ix_inbound_mail_addresses_domain_id'), 'inbound_mail_addresses', ['domain_id'], unique=False)
    op.create_index(op.f('ix_inbound_mail_addresses_organization_id'), 'inbound_mail_addresses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inbound_mail_addresses_status'), 'inbound_mail_addresses', ['status'], unique=False)
    op.create_index(op.f('ix_inbound_mail_addresses_token'), 'inbound_mail_addresses', ['token'], unique=True)
    op.create_table('smtp_inbound_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('inbound_address_id', sa.String(length=36), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=36), nullable=True),
    sa.Column('envelope_sender', sa.String(length=320), nullable=True),
    sa.Column('envelope_recipient', sa.String(length=320), nullable=False),
    sa.Column('remote_ip', sa.String(length=45), nullable=True),
    sa.Column('header_from', sa.String(length=500), nullable=True),
    sa.Column('header_to', sa.String(length=1000), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('message_id', sa.String(length=500), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('raw_path', sa.String(length=500), nullable=True),
    sa.Column('import_status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attachment_count', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inbound_address_id'], ['inbound_mail_addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smtp_inbound_messages_domain_id'), 'smtp_inbound_messages', ['domain_id'], unique=False)
    op.create_index(op.f('ix_smtp_inbound_messages_envelope_recipient'), 'smtp_inbound_messages', ['envelope_recipient'], unique=False)
    op.create_index(op.f('ix_smtp_inbound_messages_import_status'), 'smtp_inbound_messages', ['import_status'], unique=False)
    op.create_index(op.f('ix_smtp_inbound_messages_inbound_address_id'), 'smtp_inbound_messages', ['inbound_address_id'], unique=False)
    op.create_index(op.f('ix_smtp_inbound_messages_message_id'), 'smtp_inbound_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_smtp_inbound_messages_organization_id'), 'smtp_inbound_messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_smtp_inbound_messages_remote_ip'), 'smtp_inbound_messages', ['remote_ip'], unique=False)
    op.create_table('import_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=36), nullable=True),
    sa.Column('smtp_message_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('records_imported', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parser_version', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['smtp_message_id'], ['smtp_inbound_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_created_at'), 'import_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_import_jobs_file_hash'), 'import_jobs', ['file_hash'], unique=False)
    op.create_index(op.f('ix_import_jobs_organization_id'), 'import_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_import_jobs_source'), 'import_jobs', ['source'], unique=False)
    op.create_index(op.f('ix_import_jobs_status'), 'import_jobs', ['status'], unique=False)
    op.create_table('dmarc_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=36), nullable=True),
    sa.Column('import_job_id', sa.String(length=36), nullable=True),
    sa.Column('report_id', sa.String(length=500), nullable=False),
    sa.Column('reporting_org', sa.String(length=500), nullable=True),
    sa.Column('reporting_email', sa.String(length=320), nullable=True),
    sa.Column('period_begin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('policy_domain', sa.String(length=255), nullable=True),
    sa.Column('policy_adkim', sa.String(length=1), nullable=True),
    sa.Column('policy_aspf', sa.String(length=1), nullable=True),
    sa.Column('policy_p', sa.String(length=20), nullable=True),
    sa.Column('policy_sp', sa.String(length=20), nullable=True),
    sa.Column('policy_pct', sa.Integer(), nullable=True),
    sa.Column('policy_fo', sa.String(length=20), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('pass_rate', sa.Float(), nullable=True),
    sa.Column('import_source', sa.String(length=30), nullable=False),
    sa.Column('parser_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dmarc_reports_created_at'), 'dmarc_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_dmarc_reports_domain_id'), 'dmarc_reports', ['domain_id'], unique=False)
    op.create_index(op.f('ix_dmarc_reports_organization_id'), 'dmarc_reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dmarc_reports_period_begin'), 'dmarc_reports', ['period_begin'], unique=False)
    op.create_index(op.f('ix_dmarc_reports_period_end'), 'dmarc_reports', ['period_end'], unique=False)
    op.create_index(op.f('ix_dmarc_reports_policy_domain'), 'dmarc_reports', ['policy_domain'], unique=False)
    op.create_index(op.f('ix_dmarc_reports_report_id'), 'dmarc_reports', ['report_id'], unique=False)
    op.create_table('import_errors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('error_type', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_errors_job_id'), 'import_errors', ['job_id'], unique=False)
    op.create_table('inbound_mail_attachments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('import_job_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['smtp_inbound_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_mail_attachments_hash_sha256'), 'inbound_mail_attachments', ['hash_sha256'], unique=False)
    op.create_index(op.f('ix_inbound_mail_attachments_message_id'), 'inbound_mail_attachments', ['message_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=36), nullable=True),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('smtp_message_id', sa.String(length=36), nullable=True),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['dmarc_reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['smtp_message_id'], ['smtp_inbound_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_alert_type'), 'alert_events', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alert_events_created_at'), 'alert_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_alert_events_organization_id'), 'alert_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_alert_events_rule_id'), 'alert_events', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_events_severity'), 'alert_events', ['severity'], unique=False)
    op.create_index(op.f('ix_alert_events_status'), 'alert_events', ['status'], unique=False)
    op.create_table('dmarc_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=36), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('disposition', sa.String(length=20), nullable=False),
    sa.Column('dkim_result', sa.String(length=20), nullable=True),
    sa.Column('spf_result', sa.String(length=20), nullable=True),
    sa.Column('header_from', sa.String(length=255), nullable=True),
    sa.Column('envelope_from', sa.String(length=320), nullable=True),
    sa.Column('dmarc_pass', sa.Boolean(), nullable=False),
    sa.Column('spf_aligned', sa.Boolean(), nullable=False),
    sa.Column('dkim_aligned', sa.Boolean(), nullable=False),
    sa.Column('policy_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['dmarc_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dmarc_records_disposition'), 'dmarc_records', ['disposition'], unique=False)
    op.create_index(op.f('ix_dmarc_records_dkim_aligned'), 'dmarc_records', ['dkim_aligned'], unique=False)
    op.create_index(op.f('ix_dmarc_records_dmarc_pass'), 'dmarc_records', ['dmarc_pass'], unique=False)
    op.create_index(op.f('ix_dmarc_records_header_from'), 'dmarc_records', ['header_from'], unique=False)
    op.create_index(op.f('ix_dmarc_records_organization_id'), 'dmarc_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dmarc_records_report_id'), 'dmarc_records', ['report_id'], unique=False)
    op.create_index(op.f('ix_dmarc_records_source_ip'), 'dmarc_records', ['source_ip'], unique=False)
    op.create_index(op.f('ix_dmarc_records_spf_aligned'), 'dmarc_records', ['spf_aligned'], unique=False)
    op.create_table('dmarc_auth_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('auth_type', sa.String(length=10), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('selector', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['dmarc_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dmarc_auth_results_record_id'), 'dmarc_auth_results', ['record_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alert_event_id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_event_id'], ['alert_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_deliveries_alert_event_id'), 'notification_deliveries', ['alert_event_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_status'), 'notification_deliveries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_deliveries_status'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_alert_event_id'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_dmarc_auth_results_record_id'), table_name='dmarc_auth_results')
    op.drop_table('dmarc_auth_results')
    op.drop_index(op.f('ix_dmarc_records_spf_aligned'), table_name='dmarc_records')
    op.drop_index(op.f('ix_dmarc_records_source_ip'), table_name='dmarc_records')
    op.drop_index(op.f('ix_dmarc_records_report_id'), table_name='dmarc_records')
    op.drop_index(op.f('ix_dmarc_records_organization_id'), table_name='dmarc_records')
    op.drop_index(op.f('ix_dmarc_records_header_from'), table_name='dmarc_records')
    op.drop_index(op.f('ix_dmarc_records_dmarc_pass'), table_name='dmarc_records')
    op.drop_index(op.f('ix_dmarc_records_dkim_aligned'), table_name='dmarc_records')
    op.drop_index(op.f('ix_dmarc_records_disposition'), table_name='dmarc_records')
    op.drop_table('dmarc_records')
    op.drop_index(op.f('ix_alert_events_status'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_severity'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_rule_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_organization_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_created_at'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_alert_type'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_inbound_mail_attachments_message_id'), table_name='inbound_mail_attachments')
    op.drop_index(op.f('ix_inbound_mail_attachments_hash_sha256'), table_name='inbound_mail_attachments')
    op.drop_table('inbound_mail_attachments')
    op.drop_index(op.f('ix_import_errors_job_id'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index(op.f('ix_dmarc_reports_report_id'), table_name='dmarc_reports')
    op.drop_index(op.f('ix_dmarc_reports_policy_domain'), table_name='dmarc_reports')
    op.drop_index(op.f('ix_dmarc_reports_period_end'), table_name='dmarc_reports')
    op.drop_index(op.f('ix_dmarc_reports_period_begin'), table_name='dmarc_reports')
    op.drop_index(op.f('ix_dmarc_reports_organization_id'), table_name='dmarc_reports')
    op.drop_index(op.f('ix_dmarc_reports_domain_id'), table_name='dmarc_reports')
    op.drop_index(op.f('ix_dmarc_reports_created_at'), table_name='dmarc_reports')
    op.drop_table('dmarc_reports')
    op.drop_index(op.f('ix_import_jobs_status'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_source'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_organization_id'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_file_hash'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_created_at'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_smtp_inbound_messages_remote_ip'), table_name='smtp_inbound_messages')
    op.drop_index(op.f('ix_smtp_inbound_messages_organization_id'), table_name='smtp_inbound_messages')
    op.drop_index(op.f('ix_smtp_inbound_messages_message_id'), table_name='smtp_inbound_messages')
    op.drop_index(op.f('ix_smtp_inbound_messages_inbound_address_id'), table_name='smtp_inbound_messages')
    op.drop_index(op.f('ix_smtp_inbound_messages_import_status'), table_name='smtp_inbound_messages')
    op.drop_index(op.f('ix_smtp_inbound_messages_envelope_recipient'), table_name='smtp_inbound_messages')
    op.drop_index(op.f('ix_smtp_inbound_messages_domain_id'), table_name='smtp_inbound_messages')
    op.drop_table('smtp_inbound_messages')
    op.drop_index(op.f('ix_inbound_mail_addresses_token'), table_name='inbound_mail_addresses')
    op.drop_index(op.f('ix_inbound_mail_addresses_status'), table_name='inbound_mail_addresses')
    op.drop_index(op.f('ix_inbound_mail_addresses_organization_id'), table_name='inbound_mail_addresses')
    op.drop_index(op.f('ix_inbound_mail_addresses_domain_id'), table_name='inbound_mail_addresses')
    op.drop_index(op.f('ix_inbound_mail_addresses_address'), table_name='inbound_mail_addresses')
    op.drop_table('inbound_mail_addresses')
    op.drop_index(op.f('ix_alert_rules_organization_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_alert_type'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_source_ips_organization_id'), table_name='source_ips')
    op.drop_index(op.f('ix_source_ips_last_seen_at'), table_name='source_ips')
    op.drop_index(op.f('ix_source_ips_ip_address'), table_name='source_ips')
    op.drop_index(op.f('ix_source_ips_classification'), table_name='source_ips')
    op.drop_table('source_ips')
    op.drop_index(op.f('ix_organization_memberships_user_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_organization_id'), table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_notification_channels_organization_id'), table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_index(op.f('ix_domains_organization_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_app_settings_organization_id'), table_name='app_settings')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_organization_id'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_smtp_inbound_rejections_remote_ip'), table_name='smtp_inbound_rejections')
    op.drop_index(op.f('ix_smtp_inbound_rejections_created_at'), table_name='smtp_inbound_rejections')
    op.drop_index(op.f('ix_smtp_inbound_rejections_attempted_recipient'), table_name='smtp_inbound_rejections')
    op.drop_table('smtp_inbound_rejections')
    op.drop_table('plan_definitions')
    # ### end Alembic commands ###
