"""dmarcbis report format fields

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 11:52:22.247383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dmarc_records', sa.Column('override_reasons', sa.JSON(), nullable=True))
    op.add_column('dmarc_reports', sa.Column('policy_np', sa.String(length=20), nullable=True))
    op.add_column('dmarc_reports', sa.Column('policy_testing', sa.String(length=1), nullable=True))
    op.add_column('dmarc_reports', sa.Column('policy_discovery_method', sa.String(length=20), nullable=True))
    op.add_column('dmarc_reports', sa.Column('report_format', sa.String(length=10), nullable=True))
    op.add_column('dmarc_reports', sa.Column('format_evidence', sa.String(length=200), nullable=True))
    op.add_column('dmarc_reports', sa.Column('schema_version', sa.String(length=20), nullable=True))
    op.add_column('dmarc_reports', sa.Column('generator', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_dmarc_reports_report_format'), 'dmarc_reports', ['report_format'], unique=False)
    op.add_column('domains', sa.Column('dmarc_policy_np', sa.String(length=20), nullable=True))
    op.add_column('domains', sa.Column('dmarc_policy_testing', sa.String(length=1), nullable=True))
    op.add_column('domains', sa.Column('last_report_format', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'last_report_format')
    op.drop_column('domains', 'dmarc_policy_testing')
    op.drop_column('domains', 'dmarc_policy_np')
    op.drop_index(op.f('ix_dmarc_reports_report_format'), table_name='dmarc_reports')
    op.drop_column('dmarc_reports', 'generator')
    op.drop_column('dmarc_reports', 'schema_version')
    op.drop_column('dmarc_reports', 'format_evidence')
    op.drop_column('dmarc_reports', 'report_format')
    op.drop_column('dmarc_reports', 'policy_discovery_method')
    op.drop_column('dmarc_reports', 'policy_testing')
    op.drop_column('dmarc_reports', 'policy_np')
    op.drop_column('dmarc_records', 'override_reasons')
    # ### end Alembic commands ###
